version: '3.6'

services:
  retirementdashboard:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JUPYTER_ENABLE_LAB=yes
    stdin_open: true
    tty: true
    ports:
      - 8888:8888
    volumes:
      - .:/home